# Generated by Django 5.1.1 on 2024-12-08 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0002_osoba'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stanowisko',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=80)),
                ('opis', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='osoba',
            name='plec',
            field=models.CharField(choices=[('K', 'kobieta'), ('M', 'mężczyzna'), ('I', 'inne')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='osoba',
            name='stanowisko',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='folder_aplikacji.stanowisko'),
        ),
    ]
