# Generated by Django 5.1.1 on 2025-01-06 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0006_alter_osoba_options_alter_osoba_data_dodania'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
