# Generated by Django 5.1.1 on 2025-01-13 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0009_osoba_wlascicel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osoba',
            old_name='wlascicel',
            new_name='wlasciciel',
        ),
    ]
