# Generated by Django 5.1.1 on 2025-01-18 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0010_rename_wlascicel_osoba_wlasciciel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='osoba',
            options={'ordering': ['nazwisko'], 'permissions': {('view_person_other_owner', 'pozwala zobaczyć modele Osoba innych właścicieli')}},
        ),
    ]
